### ISSUE TITLE
UI issues with pydata 0.13.3

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/sphinx-book-theme#715]
### Describe the bug

Some of the UI issues I noticed are : 

- next, prev button floating up

<img width="1037" alt="Screen Shot 2023-03-31 at 12 24 31 pm" src="https://user-images.githubusercontent.com/6542997/229000018-85e7af73-22d5-429a-a677-f68d60594c56.png">

- bibliography affecting the UI

<img width="1784" alt="Screen Shot 2023-03-31 at 12 25 08 pm" src="https://user-images.githubusercontent.com/6542997/229000038-3e11e4c3-4841-460e-8dd1-9b5f855dfc01.png">

- sidebar not getting hidden

<img width="1784" alt="Screen Shot 2023-03-31 at 12 27 34 pm" src="https://user-images.githubusercontent.com/6542997/229000058-183948eb-ae79-490e-9fb4-891134ae1033.png">

- have a min-width for content

<img width="1784" alt="Screen Shot 2023-03-31 at 12 32 13 pm" src="https://user-images.githubusercontent.com/6542997/229000349-bff32243-e2d8-4926-8efc-11ad2fed3845.png">

### Reproduce the bug

1. install pydata 0.13.3 , with the latest sbt (1.0.1 about to be released)

**Comment by mmcky** [comment]
@AakashGfude some of these might be due to `docutils>0.17.1` causing issues with breaking pages when including a bibliography due to https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/322

**Comment by hotchilipowder** [comment]
Same problem

**Comment by choldgraf** [comment]
This should now be fixed

**Comment by jackshiwl** [comment]
Hi, I am still getting the same issue for the 2nd screenshot above. The bibliography will push the article footer to the right side.

**Comment by choldgraf** [comment]
I think this is fixed in the release candidate that's out now, it should be released soon in full!

**Comment by jackshiwl** [comment]
thanks for replying, just re-clarifying on this - in other words, this issue will be fixed at v0.14.5?

**Comment by agoose77** [comment]
@jackshiwl no, the RC is 1.1.0rc1, so the next version should be 1.1.0:
https://pypi.org/project/sphinx-book-theme/1.1.0rc1/

That RC is already downloadable, and should fix the problem. We're stuck on making a proper release right now because a build-time dependency is broken on one of our release platforms, and we want a working sdist.

**Comment by 12rambau** [comment]
@choldgraf it seems the issue is coming from pydata-sphinx-theme, could you point me to the PR/commit that fixed the issue so I can propagate the fix you found here ?

**Comment by jackshiwl** [comment]
any updates on this?

**Comment by agoose77** [comment]
For issues relating to `sphinxcontrib-bibtex` interaction, see https://github.com/pydata/pydata-sphinx-theme/issues/1581#issuecomment-1856907745
